# vim:ft=kitty
## name: Dracula Pro
## author: Cam Richardson, Keegan Carruthers-Smith
## license: MIT

foreground            #F8F8F2
background            #22212C
selection_foreground  #ffffff
selection_background  #454158
url_color #80FFEA
color0  #21222C
color8  #504C67
color1  #FF9580
color9  #FFAA99
color2  #8AFF80
color10 #A2FF99
color3  #FFFF80
color11 #FFFF99
color4  #9580FF
color12 #AA99FF
color5  #FF80BF
color13 #FF99CC
color6  #80FFEA
color14 #99FFEE
color7  #F8F8F2
color15 #FFFFFF
cursor            #9580FF
cursor_text_color #454158
active_tab_foreground   #282a36
active_tab_background   #f8f8f2
inactive_tab_foreground #7970A9
inactive_tab_background #504C67
mark1_foreground #7970A9
mark1_background #FF9580
